### PR TITLE
Precommit and dependency specification

### LINKED ISSUE #9: To Do: (re)-implement CI
Adding this as a reminder to myself to get the github actions up and running!

### PR DESCRIPTION
**Pull request by chrishavlin**
Updating dependency specification (no longer specifying packages multiple times), making pre-commit match the github action (will closes #9 ).

### CODE REVIEW

**Comment by chrishavlin** [comment]
reverted the linting packages due to a dependency issue, will bump in a separate PR later on...

**Comment by chrishavlin** [comment]
Added a few commits to add a github workflow to do a manifest check and I renamed `scratch_notebooks` to `examples`

**Comment by chrishavlin** [comment]
@samwalkow  and @matthewturk , either of you want to review in detail? shall we merge? (assuming that last test running also passes...)

**Comment by chrishavlin** [comment]
oh, whoops. Let me do one more quick thing

**Comment by chrishavlin** [comment]
arg, I broke something... one more thing...

**Comment by chrishavlin** [comment]
OK. Back to working as normal. 

@matthewturk , @samwalkow  - reiterating my initial question: wanna review?

**Comment by samwalkow** [comment]
@chrishavlin this all looks good to me and I'm ready to merge it! @matthewturk what do you think?

**Pull request merged**
