### PR TITLE
some package structure improvements

### PR DESCRIPTION
**Pull request by chrishavlin**
The changes here are mostly to get us closer to an installable package given all the recent work. I moved a few more files to our temporary `Previous_Analysis_Schema` directory and adjusted the  `analysis_schema/.__init__.py` to import the top level `ytModel` from `SchemaModel` so that you can do:

```python
import analysis_schema

with open("path/to/an/already/validated/jsonfile.json",'r') as jfile:
    validated_json = jfile.read()

model = analysis_schema.ytModel.parse_raw(validated_json)
results = model._run() 
```

in `setup.py` I ~~removed the `Click` dependency since we don't seem to be using it anymore and~~ adjusted the python versions (though we're obviously not actually testing anything yet...). We should probably add yt to the requirements too once yt 4.0 is out, but as of now the package requires building yt from source (that info should go somewhere -- in the readme? or maybe we can direct `setup.py` to install from github directly?). In any case, if you have the latest yt dev branch installed, you can now do `pip install -e . ` from the top level of this package and then run the above snippet (e.g., replace `"path/to/an/already/validated/jsonfile.json"` to point to `"analysis_schema/pydantic_schema_example.json"`).

I also added an unrelated fix: there was a stray `tuple` still in `ytDataClasses` that was causing an error with python 3.7.

### CODE REVIEW

**Comment by chrishavlin** [comment]
Oh! maybe we are! I'll look more carefully

**Comment by chrishavlin** [comment]
I was testing out installing the current package as it is now and I think the click dependency was pinning python at < 3.8? And I didn't realize we were actually using it so I just removed it :) I'll try it again and figure out where it's used.

**Comment by matthewturk** [comment]
I mean, we don't use a *lot* of it, but I think it's all in cli.py

**Comment by chrishavlin** [comment]
Ok, added it back! Can think about it more later since there's still work to be done in setup.py. I'll also might spend a bit of time getting the client and sever working again with the current schema, so I'll look more closely at this then.

**Comment by chrishavlin** [comment]
just added some more changes: got the server working again with the new schema (screen shot of it in action https://imgur.com/PgWEDZz ). I added to the `index.html` to capture the current state of the JSON and do something with it. For now it just prints it to another div, but it could be submitted to a GET/POST method to execute (see the screen shot).

**Pull request merged**
