### PR TITLE
'FileName' is not optional in the schema

### PR DESCRIPTION
**Pull request by samwalkow**
Made the `fn` attribute in the `Dataset` dataclass optional. This way, users can specify a dataset using the filename once, and re-use the `DatasetName` instead. 

However, this means that a user could create a _valid_ workflow without specifying a file. As discussed during the sprint, we'll create a separate way to validate that a filename exists and return an error if it does not. That functionality does not exist in this PR. 

One more note: users must always specify a dataset. Either a full dataset with the filename or with a dataset name that references that full dataset. But the `Dataset` attribute is not required, so it's confusing. I'll open another issue for this.

### CODE REVIEW

**Comment by samwalkow** [comment]
It looks one of the tests did not like that change. Looking into it further.

**Comment by chrishavlin** [comment]
Did you figure out the failing test?

It's coming from `test_execution_with_fake_ds` because the new version of `pydantic_schema_example.json` is using an additional field (the pressure field). That test does some trickery in order to run a schema without the full dataset being available: it replaces whatever dataset you specify with a fake dataset. So in that test you'll want to add a new pressure field here:

https://github.com/data-exp-lab/analysis_schema/blob/32360719d5dfc4ec7b97a8fc2e2ddd43b292bf74/tests/test_workflows.py#L73-L74

(for the `units`, you can use `'dyn/cm**2'`).

I intend to improve how that fake dataset is generated, so that it will always have whatever fields you specify. 

Oh and if you want to check locally if your fixes work, you can run `pytest -v` from the top directory and it will run all the tests.

**Comment by chrishavlin** [comment]
Oh, and I think this PR should update the workflow to validate that the workflow data_store has a filename for every short name supplied. Should happen at the end of `build_workflow`:

https://github.com/data-exp-lab/analysis_schema/blob/32360719d5dfc4ec7b97a8fc2e2ddd43b292bf74/analysis_schema/_workflows.py#L52-L81

At the end of that function, `self.data_store.available_datasets` should not have any keys without an associated  filepath/string.  If it does, should raise an error...

**Comment by samwalkow** [comment]
Thanks for pointing that out Chris! That was super helpful. I changed the field instead of adding pressure to the field list.

**Review by chrishavlin — APPROVED** [review]
Looks good! I'll follow this up with some updates to the testing....

**Pull request merged**
